CREATE DATABASE docs_db;
CREATE DATABASE quiz_db;
CREATE USER docs_user WITH PASSWORD '__DOCS_PASSWORD__';
CREATE USER quiz_user WITH PASSWORD '__QUIZ_PASSWORD__';
REVOKE ALL ON DATABASE docs_db FROM PUBLIC;
REVOKE ALL ON DATABASE quiz_db FROM PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE docs_db TO docs_user;
GRANT ALL PRIVILEGES ON DATABASE quiz_db TO quiz_user;
\connect docs_db
GRANT USAGE, CREATE ON SCHEMA public TO docs_user;
\connect quiz_db
GRANT USAGE, CREATE ON SCHEMA public TO quiz_user;
